### ISSUE TITLE
[AJUDA] Nginx não encontra host da api no teste

### ISSUE THREAD

**Issue by andreluizsgf** [zanfranceschi/rinha-de-backend-2024-q1#1067]
Olá, ao submeter o projeto para teste a criação do container falha com o seguinte erro `host not found in upstream "api01:3000"`, porém ao rodar o projeto localmente consigo subir o container normalmente.
- Realizei o build da imagem como manda o README, com `docker buildx build --platform linux/amd64`
- O nginx depende do health das apis para subir

[docker-compose.logs](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/participantes/andreluizsgf/docker-compose.logs) [docker-compose.yml](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/participantes/andreluizsgf/docker-compose.yml) [nginx.conf](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/participantes/andreluizsgf/nginx.conf)

Conseguem me ajudar a entender o que acontece, por favor?

**Comment by erikyami** [comment]
Nas linhas 97 e 98 parece que sua API está finalizando com erro:

``` 
api01-1 exited with code 1
api02-1 exited with code 1
``` 
Imagino que seja falha na comunicação com o banco de dados.

**Comment by ddanielvaz** [comment]
@andreluizsgf creio que as linhas 58 e 59 do docker-compose.yml não deveriam ser necessárias.
entretanto a falha parece ter correlação com a cross-compilação

api01-1  | exec /rinha-de-backend-2024: exec format error
api02-1  | exec /rinha-de-backend-2024: exec format error

**Comment by ddanielvaz** [comment]
api02 The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested 
 Container andreluizsgf-api02-1  Created
 api01 The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested

**Comment by hiroshimorowaka** [comment]
Eu não cheguei a testar pra te dizer isso, mas eu tenho uma suspeita:

O problema provavelmente ta na imagem de go que vc ta baixando. 

Usa a golang:1.22.0-alpine3.19 

E  se quiser forçar pra ser AMD64, usa
FROM amd64/golang:1.22.0-alpine3.19 

As informações tão no próprio hub docker do Golang

https://hub.docker.com/_/golang/
https://hub.docker.com/r/amd64/golang/

**Comment by andreluizsgf** [comment]
Pessoal, obrigado pela ajuda! <3 Acabei tendo que explicitar as networks nos serviços e a `platform: linux/amd64` na api. Fecharei a a issue

**Comment by andreluizsgf** [comment]
Pessoal, obrigado pela ajuda! <3 Acabei tendo que explicitar as networks nos serviços e a platform: linux/amd64 na api. Fecharei a a issue
