### ISSUE TITLE
Resultado rodando local diferente do que o da Submissão

### ISSUE THREAD

**Issue by vitorweirich** [zanfranceschi/rinha-de-backend-2024-q1#1099]
Olá galera!

Rodei diversas vezes minha submissão localmente e o resultado foi consideravelmente melhor do que o resultado em [STATUS-TESTES](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/STATUS-TESTES.md). 

Queria uma ajuda para saber se eu estou executando o teste de maneira errado ou se tem relação com a arquitetura da máquina X a imagem gerada.

Segue o link para a submissão: https://github.com/zanfranceschi/rinha-de-backend-2024-q1/tree/main/participantes/vitor_weirich_java

Agradeço qualquer apoio :) 

Resultados rodando localmente:
![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/70552850/a8667d54-cdbc-4c09-a68b-f498b6da5668)
![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/70552850/119cc7e0-633b-48a2-bcb0-2cb96832241d)

**Comment by zanfranceschi** [comment]
É bem normal ter variabilidade de máquina pra máquina – sua máquina deve ser mais poderosa do que [a do teste](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/SPECTESTENV.md).
