### ISSUE TITLE
CI apagando arquivo

### ISSUE THREAD

**Issue by asfernandes** [zanfranceschi/rinha-de-backend-2024-q1#1141]
Queria entender porque meu arquivo `participantes/asfernandes-cpp-haproxy-mongoose-firebird/config/haproxy.cfg` foi apagado nesse commit: 14589b2ad93fd1f7f23837b824025a47fef4ea1f

**Comment by zanfranceschi** [comment]
Apaguei por engano. Desculpe o mal entendido.
