### ISSUE TITLE
Dúvida sobre a estrutura do projeto

### ISSUE THREAD

**Issue by lpj145** [zanfranceschi/rinha-de-backend-2024-q1#12]
Vie que o projeto precisa ser composto de um Load Balance, Banco de Dados e dois serviços http

Tem problema se eu escrever uma única aplicação que faça tudo?

Um mini buffer pro banco de dados com armazenamento em fs
Um serviço http que recebe o trafego e o redireciona para duas threads usando semaforo?

Vai saber... se performance for realmente o fator determinante :see_no_evil:

**Comment by zanfranceschi** [comment]
Precisa ter o load balancer com as APIs atrás mesmo. Isso te força a pensar no estado delas com mais carinho por causa da distribuição round robin do load balancer.
