### ISSUE TITLE
Address already in use / Connection refused / Premature close

### ISSUE THREAD

**Issue by GeovaneBelisario** [zanfranceschi/rinha-de-backend-2024-q1#1205]
Olá pessoal!
Sabem me dizer se está faltando algo para eu configurar no Gatling / JDK para esses erros?
Estou executando em windows.

---- Errors --------------------------------------------------------------------
> j.n.BindException: Address already in use: getsockopt            9089 (42.96%)
> j.n.ConnectException: Connection refused: getsockopt             8077 (38.18%)
> j.i.IOException: Premature close                                 3990 (18.86%)
================================================================================

Obrigado

**Comment by GeovaneBelisario** [comment]
![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/39558529/9f688f0a-9473-4d07-a1ff-498218a84348)

**Comment by WagnerKessler** [comment]
Os testes do gatling funcionam 100% out of the box após instalado.
Os erros que ele está acusando são relacionados ao seu web server não estar aceitando conexões ou fechando as mesmas.

**Comment by GeovaneBelisario** [comment]
Certo, estou investigando. O interessante é que mesmo usando um projeto que já passou nos testes, permaneço com os mesmos erros. Estou usando esse aqui para validar:
[zan-dotnet](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/tree/main/participantes/zan-dotnet)

**Comment by WagnerKessler** [comment]
Não cheguei a rodar o projeto do Zan, mas certamente ele não submeteria algo quebrado para a própria rinha.
Você tá rodando diretamente no Linux? Se estiver no Windows, como está seu docker? Em cima do WSL?

**Comment by WagnerKessler** [comment]
Por desencargo de consciência, instala um Ubuntu no WSL, instala o docker no Ubuntu roda o compose e roda o gatling (.sh) lá.

**Comment by GeovaneBelisario** [comment]
Instalei o Ubuntu e funcionou tudo normal por ele. Vou testar por esse meio.
Obrigado 👍

**Comment by guidraghetti** [comment]
Estou com o mesmo problema aqui, mas estou rodando direto no Ubuntu. Inclusive rodei vários projetos já submetidos e todos dão problema.
