### ISSUE TITLE
Dúvida sobre Testes

### ISSUE THREAD

**Issue by densyy** [zanfranceschi/rinha-de-backend-2024-q1#1242]
Olá, pessoal!

Gostaria de tirar uma dúvida a respeito da coluna p75 do teste

https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/STATUS-TESTES.md

![image](https://imgur.com/7ACOukT.png)

![image](https://imgur.com/LjUxeUV.png)

O meu projeto ficou com um p75 muito alto, o mais alto entre todos os outros projetos
Gostaria de entender como esse número é gerado e se ter esse número muito alto é ruim

Agradeço desde já!

**Comment by carloseduribeiro** [comment]
Cara, em resumo, esses percentis ajudam a entender como a aplicação se comporta sob diferentes níveis de stress, permitindo identificar e otimizar gargalos de desempenho, etc.

O valor do p75 indica que 75% das solicitações foram atendidas mais rapidamente do que esse valor. Por exemplo, se o p75 é de 14324, isso significa que 3/4 das solicitações são foram processadas em 14324ms ou menos.

Me corrijam se eu estiver errado.

**Comment by densyy** [comment]
@carloseduribeiro, @droderuan , @zanfranceschi 

Seguindo esse raciocínio, o ideal seria que p75 tenha o menor valor possível, certo?
Já que se estiver demorando muito, outros clientes não estarão sendo atendidos naquele momento

Estou utilizando isso aqui no init.sql:
q seria esse lock que possivelmente tá causando o tempo alto no p75
```
CONSTRAINT saldo_limite CHECK (saldo >= limite * -1)
```

Na opinião de vocês seria uma má prática? Tem solução melhor pra esse problema?

Agradeço desde já! Vlw pela força pessoal!
