### ISSUE TITLE
PR errado aceito?

### ISSUE THREAD

**Issue by nclsgg** [zanfranceschi/rinha-de-backend-2024-q1#127]
Aparentemente foi aceito um PR que mudou os arquivos principais da rinha ao invés de adicionar um novo participante.

**Comment by DiegoCoronel** [comment]
Sorte que ficou identificado :) .. vai ser fácil reverter.

**Comment by flipbit03** [comment]
heads-up: O `README.md` principal foi alterado também

**Comment by isadoramsouza** [comment]
💩 @zanfranceschi corre aqui!

**Comment by zanfranceschi** [comment]
HAHAHA, obrigado gente! Foi um vacilo meu!

Já está corrigido!

**Comment by AlcivanLucas** [comment]
isso que dá o adm aprovar PR pelo celular numa tarde de sexta feira 13 kkkkkkkkkk
