### ISSUE TITLE
Nginx não consegue conectar com a API

### ISSUE THREAD

**Issue by jnariai** [zanfranceschi/rinha-de-backend-2024-q1#1301]
Olá, tenho limitados conhecimentos sobre o nginx, mas parece que está ocorrendo um erro no qual ele não consegue encontrar as APIs. É aquela situação clássica de "Na minha máquina funciona", e estou tendo dificuldades em reproduzir o erro mencionado no log. Alguém teria alguma sugestão para resolver este problema?

Os arquivos são esses:
- [docker-compose.logs](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/participantes/jnariai/docker-compose.logs)
- [docker-compose.yml](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/participantes/jnariai/docker-compose.yml)
- [nginx.conf](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/participantes/jnariai/nginx/nginx.conf)
- [Dockerfile](https://github.com/jnariai/rinha-backend-2024-q1-laravel/blob/main/docker/Dockerfile)

**Comment by zanfranceschi** [comment]
O problema parece ser com as APIs – [elas estão terminando](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/participantes/jnariai/docker-compose.logs#L103).

**Comment by jnariai** [comment]
É possível obter mais detalhes sobre o que possivelmente faz a API cair? Pois quando eu faço várias requisições ou até mesmo rodo o ` ./executar-teste-local.sh`, em nenhum momento ela caiu aqui.

**Comment by zanfranceschi** [comment]
O log que aparece no arquivo não diz muita coisa... tenta incluir mais logs ou aumentar o log level (debug, trace, etc.) pra ver se aparece o problema.

**Comment by zanfranceschi** [comment]
vou fechar a issue por falta de atividade. qq coisa, abre de novo
