### ISSUE TITLE
Teste de carga não está cobrindo o caso de multiplas requisições paralelas para o mesmo cliente

### ISSUE THREAD

**Issue by filipemacedo** [zanfranceschi/rinha-de-backend-2024-q1#142]
Fala, pessoal. Estou abrindo essa issue para reportar um problema que identifiquei. Por algum motivo uma API problemática (com Race Condition) está conseguindo passar em todos os casos do teste. A minha suspeita é que como estamos saindo com as requests com ID dos clientes randômicos, não estamos contemplando os casos de N requests paralelas de débito/crédito para o mesmo usuário.

Eu rodei no meu local um projeto de um participante que suspeitei da race condition, e fiz um script (link [aqui](https://gist.github.com/filipemacedo/1aac73d4a04e14f6be8924e78420fef9)) para testar a minha suspeita (caso queira o link do repositório participante que está com a race condition, só mandar dm). 

O script vai sair com 100 requisições paralelas e cada requisição vai tentar debitar 1000, no final da execução esperamos que o saldo do cliente (id: 1) esteja -100000. Porém, vejam o resultado:

<details>
<summary><b>Clique para expandir os responses inconsistentes</b></summary>

```json
{
  '200': 100,
  status_200: [
    { limite: 100000, saldo: -1000 },
    { limite: 100000, saldo: -3000 },
    { limite: 100000, saldo: -1000 },
    { limite: 100000, saldo: -1000 },
    { limite: 100000, saldo: -2000 },
    { limite: 100000, saldo: -4000 },
    { limite: 100000, saldo: -2000 },
    { limite: 100000, saldo: -2000 },
    { limite: 100000, saldo: -3000 },
    { limite: 100000, saldo: -5000 },
    { limite: 100000, saldo: -4000 },
    { limite: 100000, saldo: -3000 },
    { limite: 100000, saldo: -3000 },
    { limite: 100000, saldo: -3000 },
    { limite: 100000, saldo: -3000 },
    { limite: 100000, saldo: -4000 },
    { limite: 100000, saldo: -2000 },
    { limite: 100000, saldo: -3000 },
    { limite: 100000, saldo: -4000 },
    { limite: 100000, saldo: -8000 },
    { limite: 100000, saldo: -4000 },
    { limite: 100000, saldo: -6000 },
    { limite: 100000, saldo: -4000 },
    { limite: 100000, saldo: -5000 },
    { limite: 100000, saldo: -5000 },
    { limite: 100000, saldo: -4000 },
    { limite: 100000, saldo: -5000 },
    { limite: 100000, saldo: -5000 },
    { limite: 100000, saldo: -7000 },
    { limite: 100000, saldo: -6000 },
    { limite: 100000, saldo: -6000 },
    { limite: 100000, saldo: -6000 },
    { limite: 100000, saldo: -7000 },
    { limite: 100000, saldo: -6000 },
    { limite: 100000, saldo: -8000 },
    { limite: 100000, saldo: -7000 },
    { limite: 100000, saldo: -7000 },
    { limite: 100000, saldo: -8000 },
    { limite: 100000, saldo: -7000 },
    { limite: 100000, saldo: -7000 },
    { limite: 100000, saldo: -9000 },
    { limite: 100000, saldo: -8000 },
    { limite: 100000, saldo: -8000 },
    { limite: 100000, saldo: -8000 },
    { limite: 100000, saldo: -8000 },
    { limite: 100000, saldo: -10000 },
    { limite: 100000, saldo: -9000 },
    { limite: 100000, saldo: -9000 },
    { limite: 100000, saldo: -9000 },
    { limite: 100000, saldo: -9000 },
    { limite: 100000, saldo: -10000 },
    { limite: 100000, saldo: -10000 },
    { limite: 100000, saldo: -11000 },
    { limite: 100000, saldo: -10000 },
    { limite: 100000, saldo: -10000 },
    { limite: 100000, saldo: -11000 },
    { limite: 100000, saldo: -10000 },
    { limite: 100000, saldo: -11000 },
    { limite: 100000, saldo: -12000 },
    { limite: 100000, saldo: -12000 },
    { limite: 100000, saldo: -12000 },
    { limite: 100000, saldo: -11000 },
    { limite: 100000, saldo: -12000 },
    { limite: 100000, saldo: -15000 },
    { limite: 100000, saldo: -12000 },
    { limite: 100000, saldo: -13000 },
    { limite: 100000, saldo: -13000 },
    { limite: 100000, saldo: -13000 },
    { limite: 100000, saldo: -13000 },
    { limite: 100000, saldo: -14000 },
    { limite: 100000, saldo: -14000 },
    { limite: 100000, saldo: -13000 },
    { limite: 100000, saldo: -14000 },
    { limite: 100000, saldo: -14000 },
    { limite: 100000, saldo: -15000 },
    { limite: 100000, saldo: -14000 },
    { limite: 100000, saldo: -15000 },
    { limite: 100000, saldo: -15000 },
    { limite: 100000, saldo: -14000 },
    { limite: 100000, saldo: -15000 },
    { limite: 100000, saldo: -16000 },
    { limite: 100000, saldo: -15000 },
    { limite: 100000, saldo: -16000 },
    { limite: 100000, saldo: -16000 },
    { limite: 100000, saldo: -18000 },
    { limite: 100000, saldo: -17000 },
    { limite: 100000, saldo: -17000 },
    { limite: 100000, saldo: -17000 },
    { limite: 100000, saldo: -16000 },
    { limite: 100000, saldo: -17000 },
    { limite: 100000, saldo: -15000 },
    { limite: 100000, saldo: -19000 },
    { limite: 100000, saldo: -18000 },
    { limite: 100000, saldo: -18000 },
    { limite: 100000, saldo: -18000 },
    { limite: 100000, saldo: -18000 },
    { limite: 100000, saldo: -18000 },
    { limite: 100000, saldo: -17000 },
    { limite: 100000, saldo: -19000 },
    { limite: 100000, saldo: -17000 }
  ]
}
```
</details>

Reparem que a última requisição deixou o saldo do cliente como -17000. Ou seja, race condition confirmado.

Após rodar esse script, eu rodei os testes de carga para certificar que essa API seria travada, mas acabou não pegando, como vocês podem ver aqui:

![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/28747696/07718db5-ae05-4dcd-add6-7bf72d9552ef)

Estou abrindo um Pull Request para resolver esse problema.

**Comment by zanfranceschi** [comment]
Não sei se entendi corretamente, mas o principal do teste é justamente fazer várias requisições concorrentes para os mesmo clientes. Qual seria essa API problemática que mencionou, por favor?

**Comment by filipemacedo** [comment]
Opa zan. 

Eu testei o cenário onde estamos saindo com 10 requisições paralelas debitando 10000 do cliente id 1, esperamos que ele fique com -100000; como você pode ver o log das respostas disponibilizado na issue, o saldo não segue o que deveria seguir.

A minha suspeita é que não estamos saindo com requisições paralelas para o mesmo cliente id em um curto espaço de tempo e isso está camuflando o problema.

> Qual seria essa API problemática que mencionou, por favor?

Eu testei algumas outras, mas essa aqui foi a que originou o teste:

https://github.com/aysion/rinha_de_backend_2024_q1-nodejs

**Comment by filipemacedo** [comment]
Para reproduzir o problema você pode rodar a aplicação dele no seu local e executar o teste de carga, provavelmente vai passar. Depois você executa com a versão que eu disponibilizei no meu PR, ai você checa o extrato do cliente 1, ele terá 10 transações de débito, porém o saldo não estará -100000

**Comment by zanfranceschi** [comment]
Só pra eu ter certeza de que entendi o que está dizendo: o que você está reportando é que tem API em que o saldo mostrado no extrato não corresponde com as transações feitas. É isso?

**Comment by filipemacedo** [comment]
Sim. O que eu estou dizendo é que o teste está deixando passar API com Race Condition. Se quiser posso te explicar via call

**Comment by zanfranceschi** [comment]
Obrigado. Vou pensar num teste pra esse cenário.

**Comment by filipemacedo** [comment]
> Obrigado. Vou pensar num teste pra esse cenário.

O teste que eu disponibilizei está impedindo esse cenário
https://github.com/zanfranceschi/rinha-de-backend-2024-q1/pull/143

**Comment by filipemacedo** [comment]
Posso te mandar alguns repositórios que eu vi que estão com esse mesmo problema e que passaram a ser reprovados pela versão disponível no PR

**Comment by zanfranceschi** [comment]
me envia por favor

**Comment by filipemacedo** [comment]
Esses são alguns que eu vi:

https://github.com/arrudaricardo/rinha-de-backend-2024-q1-bun
https://github.dev/carls-rodrigues/rinha-backend-rust
https://github.com/aysion/rinha_de_backend_2024_q1-nodejs
https://github.com/aysion/rinha_de_backend_2024_q1-bun

**Comment by filipemacedo** [comment]
Todos esses que mencionei eu testei rodando com a versão atual do teste de carga e posteriormente rodei com a versão disponibilizada no PR. Qualquer coisa só falar.

**Comment by DiegoCoronel** [comment]
Eu testei com o código desse PR e o meu começou a falhar e quando analisei era realmente uma falha do meu lado que o teste atual não tava computando corretamente em relação ao saldo. Isso pq minha constraint de banco não permitia -10 quando por exemplo o limite era 10

**Comment by zanfranceschi** [comment]
[Melhoria no teste implementada](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/commit/ca4a789d6d71f8c7ee3af9a98ac0665deea03f13). Muito obrigado pela ajuda, @filipemacedo!
