### ISSUE TITLE
Dúvida sobre a declaração dos artefatos

### ISSUE THREAD

**Issue by mdamaceno** [zanfranceschi/rinha-de-backend-2024-q1#1532]
O caminho para o artefato declarado no diretório `participantes/nome` deve ser o mesmo declarado no projeto participante?

Não ficou claro para mim se ele serviria apenas como um verificador do que foi submetido e o que está no repo ou se o mesmo path seria o utilizado.

**Comment by zanfranceschi** [comment]
Não precisa ser o mesmo, não. No repositório do código fonte da participação, usa a estrutura que quiser.
