### ISSUE TITLE
Sugestão: instruções para o povo que usa ARM

### ISSUE THREAD

**Issue by andrepiske** [zanfranceschi/rinha-de-backend-2024-q1#23]
Ótimo vc ter mencionado o `$ lscpu`, que mostra que a máquina onde os testes vão rodar em uma arch `x86_64`!

Algumas pessoas podem ter arquiteturas locais diferentes, tipo ARM (caso de quem usa Mac M1, ou quem, por algum motivo, roda num Raspberry PI).

Para estas pessoas (eu incluso), será preciso fazer o build da imagem docker cross-arquitetura. Um simples `docker build` vai funcionar, mas vai falhar no seu servidor na hora de rodar os testes, na hora de dar o `docker run`.

Pra compilar de tal forma que funcione em um `x86_64`, é necessário rodar o `docker build` da seguinte forma:

```
$ docker buildx build --platform linux/amd64
```

Por exemplo: `$ docker buildx build --platform linux/amd64 -t ana/minha-api-matadora:latest .`

-----

Fica aqui a sugestão e deixo ao seu cargo decidir. Se preferir, posso abrir um PR adicionando isso ao readme.

**Comment by zanfranceschi** [comment]
Muito obrigado! Se puder adicionar as instruções ao README agradeço muito.
