### ISSUE TITLE
Usar Unix Sockets para conectar os containers

### ISSUE THREAD

**Issue by rogeriomm** [zanfranceschi/rinha-de-backend-2024-q1#262]
Usar Unix Sockets para inter conectar o Load Balancer, banco de dados, os 2 clientes, disponibilizando apenas a port TCP  9999 no container esta de acordo com as regras e do  bom senso da rinha? 

https://stackoverflow.com/questions/1235958/ipc-performance-named-pipe-vs-socket

**Comment by reinaldorauch** [comment]
Até onde eu compreendo sim

**Comment by zanfranceschi** [comment]
Essa safadeza tá permitida, sim kkkkk
