### ISSUE TITLE
Teste de validação incorreto

### ISSUE THREAD

**Issue by reinaldorauch** [zanfranceschi/rinha-de-backend-2024-q1#264]
Aqui a validação testa se a inserção mantém a ordem mas ali no teste ele valida inversamente, falhando essas requests de validação:

![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/2676370/98307a60-f4ce-4bb8-8f39-c79e9cc44f17)

Está errado ou tem algo que eu não estou pegando?

**Comment by danielwisky** [comment]
As últimas transações é um order by desc, eu entendo que tem que ser na ordem inversa mesmo (últimos inseridos, primeiro na lista de retorno)

**Comment by zebaroni** [comment]
O primeiro request é uma transação do tipo C
O segundo request é uma transacao do tipo D

Logo os dados no seu banco estão [C, D]

Como no endpoint para listar as transações elas sao ordenadas por data de criacao DESC, ele vai retornar:
[D, C]

Então, ultimas_transacoes[0].tipo tem que ser "D"

**Comment by zanfranceschi** [comment]
Como o pessoal falou, a ordem das transações deve ser por data desc. Se não for isso que quer dizer, reabra a issue (ou crie), pls.
