### ISSUE TITLE
Participações de grupos pequenos? 

### ISSUE THREAD

**Issue by JiroRauwers** [zanfranceschi/rinha-de-backend-2024-q1#28]
eu e um colega estamos estudando rust, e nos deparamos com essa rinha, achamos a ideia bem legal, e seria nossa primeira vez fazendo algo do tipo na linguagem. Queria confirmar se poderiamos fazer em dupla, visto que em nenhum momento ficou claro sobre!

Não temos experiencia nenhum com a linguagem visto que ambos trabalhamos com node. Mas achamos que esse projeto seria uma ótima "desculpa" para focarmos mais nesse estudo que vem sendo negligenciado a tempo :)

**Comment by zanfranceschi** [comment]
pode fazer, sim! individual, em dupla, trio, 350 pessoas, como vcs quiserem!
