### ISSUE TITLE
[Ajuda] Algum erro que não foi exibido no docker-compose.logs

### ISSUE THREAD

**Issue by gabrielfmagalhaes** [zanfranceschi/rinha-de-backend-2024-q1#283]
Opa @zanfranceschi, tudo joia meu caro? Dei uma olhada nos status de execução da minha submissão, vi que está marcado como falha, mas não consegui identificar nenhum erro no docker-compose. Consegue me dar uma força se é algo nos logs que não estou vendo ou o problema está aqui entre a cadeira e o teclado? rs

Tive um pouquinho de dificuldade também pra executar na minha máquina. Pra eu conseguir bater com o nginx local aqui, tive que usar um host network diferente do docker-compose que dei submissão... não sei se é isso afetando, mas como não consegui ver nada nos logs de erro 500, não identifiquei 100%

Logs: https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/participantes/gabrielfmagalhaes/docker-compose.logs

**Comment by zanfranceschi** [comment]
Tudo bem, amigo? Sua API está respondendo isso aqui nas requisições pra extrato e isso faz com que o teste não inicie. Não tem nenhum log extra sendo gerado, só o response mesmo.

![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/1862567/5847ed67-16db-44dd-85af-209c5a36e553)

Vou fechar a issue. Qualquer coisa, abre de novo ou abre outra, ok?
