### ISSUE TITLE
Data limite diferentes

### ISSUE THREAD

**Issue by willamesyano** [zanfranceschi/rinha-de-backend-2024-q1#3]
Achei essas duas datas limite no README.

"A data limite para enviar sua submissão é **2024-03-10T23:59:59-03:00**."
e
"A data/hora limite para fazer pull requests para sua submissão é até **2024-03-29T23:59:59.000-03:00"**

Qual devemos considerar? 

Att,

**Comment by zanfranceschi** [comment]
A data que vale é `2024-03-10T23:59:59-03:00`. Essa segunda foi um placeholder que me esqueci de mudar. Obrigado pela issue!
