### ISSUE TITLE
Teste integridade do extrato em race condition

### ISSUE THREAD

**Issue by gustavoramos00** [zanfranceschi/rinha-de-backend-2024-q1#300]
Existe ou vai existir algum teste para avaliar a integridade do extrato durante transações?
Ex: DURANTE o registro das 10 primeiras transações, ao consultar o extrato em paralelo, a soma das transações deve bater com o saldo total do próprio extrato.

Aproveito para sugerir que aceite o HTTP STATUS 400 quando a request estiver fora do padrão esperado (valor como float, length(descricao) > 10, etc)

**Comment by zanfranceschi** [comment]
> Existe ou vai existir algum teste para avaliar a integridade do extrato durante transações?

**Comment by zanfranceschi** [comment]
> Existe ou vai existir algum teste para avaliar a integridade do extrato durante transações?

Opa, existe sim. Uma das validações do teste é [enviar várias transações simultâneas de consultar o saldo](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/dd8ff36ceac650bf5fa0f787e7841c7aa71f4879/load-test/user-files/simulations/rinhabackend/RinhaBackendCrebitosSimulation.scala#L114).

> Aproveito para sugerir que aceite o HTTP STATUS 400 quando a request estiver fora do padrão esperado (valor como float, length(descricao) > 10, etc)

Sobre o HTTP 400 poderia ser um boa, mas como já iniciou a rinha, deixo pra uma próxima pra não mudar as regras durante o jogo, tá? Mas obrigado pela sugestão!

**Comment by gustavoramos00** [comment]
Pelo que entendi esse teste que vc citou faz 25 operações paralelas e DEPOIS verifica se deu certo.

O cenário que mencionei é diferente e só poderia ser validado nas primeiras 10 transações do cliente. Vou tentar explicar de outra forma:

Considerando aquele modelo de BD relacional, para realizar um crédito na conta do cliente é preciso fazer duas operações no BD: Atualizar o saldo e Inserir o crédito na tabela de transação. Se essas duas operações não forem feitas numa mesma "transação de BD", a consulta de extrato pode trazer um saldo total com esse crédito mas a transação ainda não estar presente mas "ultimas_transacoes", entendeu?

Sobre o HTTP 400, ele poderia ser adicionado a lista de status esperados, para não quebrar quem já vez retornando 422.
