### ISSUE TITLE
docker-compose ou docker compose?

### ISSUE THREAD

**Issue by asfernandes** [zanfranceschi/rinha-de-backend-2024-q1#318]
Os testes serão rodados com `docker compose` ou `docker-compose`?

**Comment by gutkedu** [comment]
docker compose, o docker-compose é um comando da cli da versão antiga do Docker compose

**Comment by gabrielfmagalhaes** [comment]
dúvida honesta aqui, tem diferença na execução? achava que era só pra subir o ambiente

**Comment by zanfranceschi** [comment]
Como o colega disse, os testes estão usando `docker compose` – versão atual.
