### ISSUE TITLE
load balancer é realmente necessário?

### ISSUE THREAD

**Issue by gustavolaux** [zanfranceschi/rinha-de-backend-2024-q1#322]
minha dúvida é basicamente se o load balancer é realmente um componente obrigatório já que o docker compose permite a [configuração de réplicas](https://docs.docker.com/compose/compose-file/deploy/#replicas)

**Comment by sleipnir** [comment]
Neste caso teria que adicionar `endpoint_mode: dnsrr`além do `mode: replicated` na definição dos serviços.
Ótima pergunta @gustavolaux. 
Eu acho que nem todos as submissões suportariam esse modo de operação. Mas é uma boa para aqueles que possam suportar.

**Comment by gustavoramos00** [comment]
Veja a issue #295

**Comment by gustavolaux** [comment]
perdão, não tinha visto. valeu
