### ISSUE TITLE
Sobre utilizacao do Redis no desafio 

### ISSUE THREAD

**Issue by gavageovanni** [zanfranceschi/rinha-de-backend-2024-q1#342]
Em conversa com o nobre amigo @rochajg sobre a possibilidade de utilizaçao de um redis ou outra ferramenta tipo etcd só pra fazer lock distribuido, e usar um postgres ou um sqlite pra armazenar os dados.. isso foge a regra do desafio ? 

@zanfranceschi

**Comment by zanfranceschi** [comment]
Não foge, não. Pode fazer assim, sim.
