### ISSUE TITLE
Duvida sobre o p75 geral

### ISSUE THREAD

**Issue by gutkedu** [zanfranceschi/rinha-de-backend-2024-q1#424]
Nos resultados dos testes parciais da rinha, alguem pode me explicar o que é aquele dado **p75 geral**, como funciona aquele numero?

**Comment by agpsl** [comment]
No contexto do teste, é a média de tempo de resposta obtida levando em consideração os melhores (75%) resultados, descartando-se os piores 25%.

Note que além do p75, o teste ainda retorna o p50, p95 e p99:

![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/155735935/eb999f78-fc2c-483b-bf13-61e4a8718668)

**Comment by zanfranceschi** [comment]
oi, @gutkedu!

O p75 é o 75º percentil e significa que 75% dos tempos de respostas estão sendo em até esse valor. Ou seja, são os 25% piores tempos de resposta.

Se fosse o p99 (99º percentil), seriam os 1% piores tempos de resposta – uma métrica bem rígida, grosseiramente falando.
