### ISSUE TITLE
O arquivo `quantos-testes-faltam?.sh` não funciona no Windows e está impedindo o pull

### ISSUE THREAD

**Issue by giggio** [zanfranceschi/rinha-de-backend-2024-q1#444]
Log:

```
From https://github.com/zanfranceschi/rinha-de-backend-2024-q1
 * branch            main       -> FETCH_HEAD
   cbfaccd..0cf9aa9  main       -> upstream/main
error: invalid path 'quantos-testes-faltam?.sh'
Updating 3c1d0e3..0cf9aa9
```

Sugiro retirar a `?`.

**Comment by hiroshimorowaka** [comment]
O meu ta dando esse erro tb, eu ia abrir essa Issue agora kkkkk, tive que editar os arquivos por dentro do github pra re-testar minha API

**Comment by zanfranceschi** [comment]
putz... nem era pra eu versionar isso kkkk

é meu bash ansiedade pra saber quantas apis falta pra testar... [removido](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/commit/2d11b46414865a12bb0c82a680000ba5c1c9a5e0).
