### ISSUE TITLE
Duvida sobre banco de dados em memória

### ISSUE THREAD

**Issue by victorfonsec4** [zanfranceschi/rinha-de-backend-2024-q1#475]
Poderia esclarecer:

>Exceto bancos de dados que têm como principal característica o armazenamento de dados em memória

Se um banco de dados armazena tudo em memoria e possui um thead pra descarregar a memória em disco de forma asincrona, seria desqualificado?
 
Redis tem features pra persistir dados em disco assim como outros DBs tem features pra cachear rows e outros elementos do banco de dados em memória.

**Comment by tonyldo** [comment]
Acredito q será desqualificado onde nas características primárias do banco de dados não existir escrita em disco. Mesmo bancos de dados em memória q tenham a possibilidade de persistência não é a característica principal do mesmo.

**Comment by victorfonsec4** [comment]
O que configura caracteristica principal? Se eu escrever um banco de dados que guarda a 99% do banco em cache e faz escritas em disco asincronas isso seria desqualificado? E se for 80% em memoria? 60%?

Talvez um dos requisitos seja escrever em disco antes de retornar uma resposta ao cliente?

**Comment by tonyldo** [comment]
Você consegue manter o dado somente em memória com PostgreSQL ou MySQL!? acho q aí está a resposta

**Comment by victorfonsec4** [comment]
Imagina o exemplo discutido: https://github.com/zanfranceschi/rinha-de-backend-2024-q1/issues/4

Redis pode ser usado como um intermediario mas nao como um banco final.

Eu seto meu programa pra usar o redis como um banco de dados e um job que roda a cada T segundos pra salvar o que ta no redis para o disco (salvando no postgres ou qqr outro db). Eu efetivamente estaria usando redis como o db principal mas tambem salvaria os dados em disco, de acordo com as regras acho que estaria ok mas acho não segue o espirito.

**Comment by tonyldo** [comment]
Nem tinha visto essa thread... Mas então qual era a dúvida mesmo? :)

**Comment by zanfranceschi** [comment]
> mas acho não segue o espirito

é isso, amigo...

ninguém vai ficar validando código por código e eu pedi para não usarem memória como armazenamento principal. isso pode abrir um leque enorme de discussões sobre o assunto com muitas interpretações e nuances que acho que fogem um pouco do que é a rinha.
