### ISSUE TITLE
Banco de dados em tmpfs

### ISSUE THREAD

**Issue by asfernandes** [zanfranceschi/rinha-de-backend-2024-q1#478]
Tem gente colocando o banco de dados em tmpfs.

Isso é válido?

**Comment by zanfranceschi** [comment]
não é não...

é como acabei de responder em outra issue: é inviável pra mim ficar validando código por código e se a pessoa está fazendo isso de má fé, é uma pena, até mesmo porque não tem nenhum prêmio pra quem ganhar.

inclusive, se a pessoa se destacar na rinha, as pessoas vão naturalmente querer ver o repo e vão descobrir que estavam usando coisas fora das regras e talvez fique até feio...
