### ISSUE TITLE
Descricão da transação e valor estão inconsistentes

### ISSUE THREAD

**Issue by giggio** [zanfranceschi/rinha-de-backend-2024-q1#49]
Há casos em que o campo descrição está sendo enviado com mais de 10 caracteres ou vazio. Peguei estes dois logo no começo do teste.

https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/e1729f3ce3bdb94989d85f1e321b479f3a88b964/load-test/user-files/simulations/rinhabackend/RinhaBackendCrebitosSimulation.scala#L196

e

https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/e1729f3ce3bdb94989d85f1e321b479f3a88b964/load-test/user-files/simulations/rinhabackend/RinhaBackendCrebitosSimulation.scala#L203

e

https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/e1729f3ce3bdb94989d85f1e321b479f3a88b964/load-test/user-files/simulations/rinhabackend/RinhaBackendCrebitosSimulation.scala#L210

A especificação no README diz que o campo é obrigatório, e que deve ter entre 1 e dez caracteres:
https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/e1729f3ce3bdb94989d85f1e321b479f3a88b964/README.md?plain=1#L32

Seria bom esclarecer e corrigir, afinal o campo é mesmo obrigatório? Tem mesmo esse limite de dez caracteres?

Percebi que o mesmo está acontecendo para o valor. O README diz que deve ser um inteiro:

https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/e1729f3ce3bdb94989d85f1e321b479f3a88b964/README.md?plain=1#L30

Mas nos testes vemos um decimal:

https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/e1729f3ce3bdb94989d85f1e321b479f3a88b964/load-test/user-files/simulations/rinhabackend/RinhaBackendCrebitosSimulation.scala#L182

**Comment by leoralph** [comment]
Eu acho que isso é para simular envio errado por parte do client, a api tem que estar preparada para retornar 422 caso seja menor que 1, maior que 10 ou nulo, pelo menos foi o que eu entendi

**Comment by zebaroni** [comment]
Esses testes são justamente pra testar se sua API ta tratando o erro e retornando o 422

**Comment by giggio** [comment]
Galera, prestem atenção na descrição do issue: o README diz uma coisa e os testes fazem outra. **Esse é o problema**.

**Comment by zebaroni** [comment]
Não entendi, os testes que você citou estão esperando o status 422 na requisição.
- Manda um payload errado
- Espera o 422

Se retornar 200. o teste quebra

**Comment by zanfranceschi** [comment]
@giggio é como o pessoal falou, esses testes estão validando se o retorno é um 422 para esses casos de payload inválido.

Note o `.check(status.in(422))` – a API precisa retornar um 422 nesses requests para passar nos testes.

![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/1862567/7903ee7b-aa38-4ca9-aa45-858c0f390ede)

**Comment by giggio** [comment]
@zanfranceschi Sem problemas, mas então é necessário atualizar o readme, a especificação está confusa. O único local onde aparece que o retorno de um 422 no readme é:

> Se uma requisição para débito for deixar o saldo inconsistente, a API deve retornar HTTP Status Code 422 sem completar a transação! O corpo da resposta nesse caso não será testado e você pode escolher como o representar.
