### ISSUE TITLE
Quando a aplicação inicia ela tem que tentar ler do banco de dados?

### ISSUE THREAD

**Issue by tivrfoa** [zanfranceschi/rinha-de-backend-2024-q1#521]
O teste só funciona com os limites iniciais e nenhuma transação, então eu posso considerar que o banco de dados está sempre vazio quando a aplicação inicia?

Quando a aplicação inicia ela precisa excluir as transações existentes?

**Comment by zanfranceschi** [comment]
Isso, não pode ter nenhuma transação feita antes do teste.
