### ISSUE TITLE
Dúvida script de testes

### ISSUE THREAD

**Issue by brunogs** [zanfranceschi/rinha-de-backend-2024-q1#599]
Oi @zanfranceschi, 

Acha que faz sentido adicionar uma validação da arquitetura minima no script executar-teste-local ?
Tinha pensado em algo bem simples, tipo validar mínimo de containers:

```bash
num_containers=$(docker ps -q | wc -l)
if [ "$num_containers" -ge 4 ]; then
    .... ok é no mínimo 4
else
    ... para o teste
fi
```

E talvez fazer algo com ```docker stats --no-stream --format ... ``` para pegar a memória total.

A ideia é tentar ajudar/alertar quem tá fazendo errado por engano.
Se fizer sentido, posso tentar abrir um PR.

Até mais!

**Comment by RodolphoVSantoro** [comment]
Será que 4 faz sentido mesmo?
Talvez 3, pra quem fez algum banco que rode integrado na própria API
Ou entendi errado os requerimentos do desafio?

**Comment by zanfranceschi** [comment]
oi bruno, valeu pela disposição, mas talvez fique muito complexo... 🙏🏻
