### ISSUE TITLE
Validação de float

### ISSUE THREAD

**Issue by lobomfz** [zanfranceschi/rinha-de-backend-2024-q1#6]
Uma das validações, é enviado o valor de 1.0 esperando o resultado 422. No js, 1.0 e 1 são funcionalmente identicos, seria possivel alterar o valor do teste para algum float "real", como 1.2?

**Comment by zanfranceschi** [comment]
mas é claro!

https://github.com/zanfranceschi/rinha-de-backend-2024-q1/commit/430cd191984e6729bee9e69de97efe072ea8876e
