### ISSUE TITLE
Teste de performance pode iniciar antes do fim dos testes de critérios, causando falsos negativos.

### ISSUE THREAD

**Issue by felipemarkson** [zanfranceschi/rinha-de-backend-2024-q1#670]
Nas seguintes linhas:

https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/80933286f8b7ba7a2007775d94ff68a2ddbdd393/load-test/user-files/simulations/rinhabackend/RinhaBackendCrebitosSimulation.scala#L300-L310

O teste `criteriosClientes` acontece em paralelo com `criterioClienteNaoEcontrado`.

Se o resultado de `criterioClienteNaoEcontrado` retornar antes da finalização de `criteriosClientes`, o teste de perfomance irá inicializar, causando falsos negativos no teste `criteriosClientes`, pois quando se faz o request do extrato, requisições do teste perfomance já podem ter sido iniciadas.

A solução seria adicionar um `andThen` para que o test de perfomance se inicie apenas após o teste, `criteriosClientes`.

```scala
).andThen(
  criteriosClientes.inject(
    atOnceUsers(saldosIniciaisClientes.length)
  ).andThen( // AQUI!
  criterioClienteNaoEcontrado.inject(
    atOnceUsers(1)
  ).andThen(
    debitos.inject(
      rampUsersPerSec(1).to(220).during(2.minutes),
      constantUsersPerSec(220).during(2.minutes)
    ),
```

Podem confirmar se eu entendi certo? Não tenho experiência com Gatling :(

**Comment by zanfranceschi** [comment]
Dei uma olhada aqui e tá certo mesmo. O próximo cenário (seguido de `andThen`) não começa antes de todos os anteriores terminarem. Ufa, não vou ter que testar tudo de novo kkkk

**Comment by felipemarkson** [comment]
Vishe, eu to com algum problema então. Porque tá dando problema exatamente nesse cenário. quando eu coloco o `andThen` volta a funcionar...

**Comment by felipemarkson** [comment]
Oi, eu consegui criar um exemple minino que reproduz esse problema:

https://github.com/felipemarkson/rinhatest

É em JavaScript, mas acho que qualquer linguagem com async é possível reproduzir.
