### ISSUE TITLE
NGINX: worker_connections are not enough

### ISSUE THREAD

**Issue by matheuswr89** [zanfranceschi/rinha-de-backend-2024-q1#694]
Atualmente, estou trabalhando em outro projeto para a rinha, utilizando o Spring Webflux. No entanto, tenho enfrentado um problema recorrente ao executá-lo no meu sistema: após aproximadamente 3000 requisições, ele apresenta o erro mencionado no título desta issue. Esse mesmo problemas acontece em alguns dos outros projetos baseados em Webflux que encontrei por aqui e executei na minha maquina.

Já tentei resolver o problema aumentando o limite NOFILE do Linux, tanto utilizando o comando `prlimit` quanto adicionando algumas configurações ao arquivo `/etc/sysctl.conf`. E mesmo se eu alterar o arquivo `nginx.conf` colocando um worker_connections alto, em algum momento esse problema ataca novamente.

Alguém poderia sugerir possíveis soluções para esse problema?

**Comment by hiroshimorowaka** [comment]
Manda o repositório da sua API pra eu dar uma olhada.

**Comment by zanfranceschi** [comment]
Provavelmente, está havendo contenção em outro serviço (banco ou api) e isso faz com que conexões se acumulem no Nginx. Por isso, talvez o problema não seja com o Nginx.

**Comment by zanfranceschi** [comment]
Btw, posta isso no twitter que acho que tem mais chance de mais pessoas responderem. Cola o link dessa issue lá se quiser.

**Comment by matheuswr89** [comment]
Consegui "mitigar" aqui. Agora é tentar melhorar a performance. Valeu pela ajuda pessoal!
