### ISSUE TITLE
[AJUDA] - Minha api cai assim que ela inicia

### ISSUE THREAD

**Issue by franklaercio** [zanfranceschi/rinha-de-backend-2024-q1#708]
## Problema
Assim que a api inicia os testes, ela é derrubada, rodei localmente várias vezes e não consigo identificar qual é o problema, pois em todas as execuções os testes passam com sucesso.

Em cada teste local, eu tento limpar todo o lixo do Docker rodando o comando abaixo

```shell
docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker rmi $(docker images -q) && docker volume rm $(docker volume ls -q) && docker compose up
```

- [Logs da execução](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/main/participantes/franklaercio/docker-compose.logs)
- [Repositório](https://github.com/franklaercio/rinha-de-backend-java)

## O que já tentei
- Retirar commits assíncronos e outras bruxarias do Postgres
- Diminuir o pool de conexões do ngnix
- Aumentar a memória das apis

## O que observei
Vi que a aplicação está consumindo toda a memória disponível, mas não consigo encontrar onde existem vazamentos de memória ou bugs.

![Screenshot from 2024-02-21 12-55-49](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/38151364/29ce4b4a-e430-43f7-a804-ebbe46b2de1b)

Se alguém passou por isso ou queira ajudar, agradeço demais!

**Comment by franklaercio** [comment]
_Atualização_

Abri este PR abaixo aumentando mais ainda a memória da aplicação após perceber que estava usando por volta de 200Mb, quando disponibilizava 500Mb para cada instância.

![Screenshot from 2024-02-21 14-17-26](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/38151364/a46f56ec-f880-4cb5-8be1-c7d4ffccbb98)

[Pull request mencionado](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/pull/712)

**Comment by gldmelo** [comment]
dei uma olhada no seu log. Algo que podes experimentar é usar um **healthcheck** no banco pra ter certeza de que o serviço está ativo. Pode ser que os primeiros requests estão sendo perdidos pq o serviço não está totalmente "em pé". Eu tive que implementar isso para a minha versão com o Python pois a api iniciava tão rápido que o banco ainda não estava pronto pra receber conexões e dava erro na inicialização.

Veja nas linhas 78 e seguintes do log mensagens alternadas do banco e do nginx. algumas mensagens de erro aparecem antes mesmo da mensagem inicial do java informando que está pronto.

**Comment by franklaercio** [comment]
Funcionou aqui, o que tive que fazer foi apenas ajustar o pool de conexões e a memória para os seguintes parâmetros para rodar com Spring Web Flux:

- API com 200M
- Banco de dados com 140M
- Ngnix com 10M

- Work connections com 1000
