### ISSUE TITLE
Dúvida sobre Validação de Transações Concorrentes

### ISSUE THREAD

**Issue by thiper01** [zanfranceschi/rinha-de-backend-2024-q1#826]
Olá, estou testando minha API e estou tendo o único problema de `jmesPath(saldo.total).find.is(0), but actually found -25` dei uma olhada no script de testes e reparei isso aqui.

```
validacaoTransacoesConcorrentes("d").inject(
      atOnceUsers(validacaConcorrentesNumRequests)
    ).andThen(
      validacaoTransacoesConcorrentesSaldo(validacaConcorrentesNumRequests * -1).inject(
        atOnceUsers(1)
      )
    ).andThen(
      validacaoTransacoesConcorrentes("c").inject(
        atOnceUsers(validacaConcorrentesNumRequests)
      ).andThen(
        validacaoTransacoesConcorrentesSaldo(0).inject(
          atOnceUsers(1)
        )
      )
    )
```
Sendo que essas validações são sempre feitas no cliente id 1 de acordo com:
```
val validacaConcorrentesNumRequests = 25
  val validacaoTransacoesConcorrentes = (tipo: String) =>
    scenario(s"validação concorrência transações - ${tipo}")
    .exec(
      http("validações")
      .post(s"/clientes/1/transacoes")
          .header("content-type", "application/json")
          .body(StringBody(s"""{"valor": 1, "tipo": "${tipo}", "descricao": "validacao"}"""))
          .check(status.is(200))
    )
  
val validacaoTransacoesConcorrentesSaldo = (saldoEsperado: Int) =>
    scenario(s"validação concorrência saldo - ${saldoEsperado}")
    .exec(
      http("validações")
      .get(s"/clientes/1/extrato")
      .check(
        jmesPath("saldo.total").ofType[Int].is(saldoEsperado)
      )
    )
```

Logo, se eu entendi direito como é pra o crédito e débito funcionar na rinha, esse script faz com que o saldo do cliente 1 fique em -25 através das transações de débito e passando na primeira validação, porém quando é realizada a segunda validação utilizando crédito, apesar de o saldo não ser afetado pelas transações de crédito, o cliente 1 continua com -25 de saldo do teste anterior, falhando a verificação de estar com 0 de saldo no segundo teste. 
A ordem não deveria ser ao contrário, crédito primeiro e débito depois? Ou eu entendi o crédito e débito errado?

**Comment by zanfranceschi** [comment]
A ordem é essa mesma: 25 débitos de 1 deixando o saldo em -25 (esperado) e depois 25 créditos de 1 deixando o saldo em 0 (esperado).

**Comment by thiper01** [comment]
Faz total sentido, tinha entendito crédito tipo uma compra no cartão de crédito, valeu

**Comment by zanfranceschi** [comment]
boa, talvez se eu tivesse usado retirada de depósito teria ficado mais claro mesmo!
