### ISSUE TITLE
Pode mais de um projeto por participante?

### ISSUE THREAD

**Issue by Mourishitz** [zanfranceschi/rinha-de-backend-2024-q1#83]
Notei no exemplo que a participante metafórica Ana adicionou em `participantes` um diretório `ana-01`..

Pessoas que quiserem realizar mais de uma versão do desafio podem mandar com esse padrão de nomes? Ex.: `ana-01` para um app em PHP e `ana-02` para um app em Rust

**Comment by zanfranceschi** [comment]
pode quantos quiser!
