### ISSUE TITLE
[Ajuda] Logs de erro docker-compose.logs

### ISSUE THREAD

**Issue by MuriloChianfa** [zanfranceschi/rinha-de-backend-2024-q1#90]
Fala meu mano @zanfranceschi, fui olhar os status de execução da minha submissão, mas não encontrei os erros no [docker-compose.logs](/zanfranceschi/rinha-de-backend-2024-q1/tree/main/participantes/murilochianfa/docker-compose.logs), talvez porque o arquivo deve estar limitado em 500 linhas talvez, ou eu que não vi algo?

Apropósito, grande iniciativa, muito show a ideia da rinha :)

**Comment by zanfranceschi** [comment]
boa! valeu!

trunquei os arquivos porque tem api que loga todos os requests e aí fica com vários e vários megas... vou dar uma olhada na sua API pra ver se consigo te ajudar no troubleshooting

**Comment by zanfranceschi** [comment]
tá rodando agora... tenho a impressão que sua api (docker pull, start up, etc.) não terminou em menos de 45 segundos. mas agora tá indo!
![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/1862567/ed2a3a07-2631-45c1-80d7-ed9f4fe5a4ed)

**Comment by zanfranceschi** [comment]
só o decote do seu teste
![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/1862567/dc0e10fb-9dbe-4bc6-b413-35da27039dea)
