### ISSUE TITLE
GOMAXPROCS

### ISSUE THREAD

**Issue by skhaz** [zanfranceschi/rinha-de-backend-2024-q1#900]
I'm not closely following the event, but one detail that even the most experienced Go developers often forget in containerized environments is to correctly set the GOMAXPROCS, as mentioned in the article below. In certain situations, it can harm performance.

https://www.ardanlabs.com/blog/2024/02/kubernetes-cpu-limits-go.html

**Comment by zanfranceschi** [comment]
Obrigado pela contribuição.
