### ISSUE TITLE
Validação de strings

### ISSUE THREAD

**Issue by asfernandes** [zanfranceschi/rinha-de-backend-2024-q1#92]
Nas validações de quantidade de caracteres, podemos assumir que todas as strings serão ascii (sem caracteres especiais)?

**Comment by zanfranceschi** [comment]
Sim. Os caracteres possíveis são A-Z, a-z, 0-9

https://github.com/zanfranceschi/rinha-de-backend-2024-q1/blob/f8199b6fca9d8dc2ae48b0a9634467f22e432c1d/load-test/user-files/simulations/rinhabackend/RinhaBackendCrebitosSimulation.scala#L18


https://dotty.epfl.ch/api/scala/util/Random.html#alphanumeric-0
