### ISSUE TITLE
Erro validação: jmesPath(saldo.total).find.is(-25), but actually found -3	

### ISSUE THREAD

**Issue by jcrjuliano** [zanfranceschi/rinha-de-backend-2024-q1#994]
Olá, não sei se mais alguém está com esse problema, mas essa validação é a única que está dando problema...

Meu projeto está aqui: https://github.com/jcrjuliano/rinha-q1

![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/11932780/af56eef4-92ab-4953-a516-a9d29d211b29)

Já fiz e refiz a lógica várias vezes, inicialmente eu havia feito o código usando design patterns (strategy e factory) para ficar organizado, porém, removi tudo e joguei no controlador direto para diminuir a quantida de beans, mas mesmo assim esse erro não se resolve.

E o estranho que é meio intermitente, e as vezes há uma outra validação que também da o erro:
![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/11932780/b9cab163-bec3-4454-b8e5-89c4fb9aa449)

Obrigado.

**Comment by jeifersonalmeida** [comment]
Olhando rapidamente sua implementação me parece que você não está fazendo controle de transação na comunicação da sua API com o banco de dados. Nessa edição da rinha o foco é concorrência e no início do teste são realizadas várias chamadas concorrentes em cima do mesmo cliente debitando e depois creditando saldo, se a aplicação não bloquear o dado no banco esse problema vai acontecer. Estava acontecendo comigo também e só resolveu quando dei uma atenção especial nisso.

Dica: desabilite o auto commit do banco e use "SELECT FOR UPDATE".

**Comment by jcrjuliano** [comment]
Boa @jeifersonalmeida  deu certo! Fiz umas alterações seguindo a linha do select for update e resolveu o problema. Muito obrigado pela dica!
Agora sim os resultados ficaram bonitos:
![image](https://github.com/zanfranceschi/rinha-de-backend-2024-q1/assets/11932780/d2ddddb0-2830-479b-9cc2-525e6fc08f3b)
